name: Download File

on:
  workflow_dispatch:
    inputs:
      FILE_URL:
        description: 'FILE_URL'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Download File
        run: aria2c "${{ github.event.inputs.FILE_URL }}"

      - name: Get Downloaded Filename
        id: filename
        run: echo "filename=$(ls -t | head -1)" >> $GITHUB_OUTPUT

      - name: Create Release on GitHub
        uses: softprops/action-gh-release@v3
        with:
          draft: true
          files: ${{ steps.filename.outputs.filename }}
