name: Download File

on:
  workflow_dispatch:
    inputs:
      FILE_URL:
        description: 'FILE_URL'
        required: true

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download File
        run: aria2c "${{ github.event.inputs.FILE_URL }}"

      - name: Get Downloaded Filename
        id: filename
        run: echo "filename=$(ls -t | head -1)" >> $GITHUB_OUTPUT

      - name: Set Version Info
        id: version
        run: echo "version=v$(date +%Y-%m-%d-%H%M)" >> $GITHUB_OUTPUT

      - name: Create Release on GitHub
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ steps.version.outputs.version }}
          files: ${{ steps.filename.outputs.filename }}
          name: ${{ steps.version.outputs.version }}
          body: |
            file from: ${{ github.event.inputs.FILE_URL }}
